### ISSUE TITLE
Progressive addition...

### ISSUE THREAD

**Issue by tddewey** [10up/generator-wp-make#1]
We don't always start with WordPress... But that's where we often end up...

Does it make sense to have a way to scaffold a project that's going to start as html, css, and a bit of JS — then have a sub-generator that adds in the WP specific items: functions.php, style.css boilerplate, screenshot.png, pot files, etc?

That way we could start with a minimal project to quickly get in browser, but have a defined scaffold for layering in the WP stuff when it comes time to actually make it into a theme?

**Comment by lkwdwrd** [comment]
Closing as I think this has been open a really long time and hasn't gotten any additional traction. It's possible a sub-generator could be spun up for this, but at this point, let's stay focused on WP tooling.
