### ISSUE TITLE
Consolidate shared code

### ISSUE THREAD

**Issue by lkwdwrd** [10up/generator-wp-make#10]
While themes and plugins are fairly separate, there is a fair bit of code in each of the generators that is the same. It would be very nice to consolidate the various templates into a single file to ease maintenance going forward so that a change made to the Gruntfile in a plugin doesn't also have to be made in the theme and child-theme generators.

I was able to accomplish it in my [vvv-generator](https://github.com/lkwdwrd/generator-vvv) but never got around to refactoring this generator to make use of shared code.

**Comment by ericmann** [comment]
Shared code now lives in the `/shared` directory.
