### ISSUE TITLE
'$ grunt test' fails in plugin

### ISSUE THREAD

**Issue by lkwdwrd** [10up/generator-wp-make#14]
You should be able to run `grunt test` to invoke both the PHPUnit and QUnit tests, but they are both failing in the current setup on a fresh plugin install. PHP Unit doesn't run any tests and QUnit is failing to run.

First `bootstrap.php` was changed to `bootstrap.php.dist`. I updated the generated `Gruntfile.js` ang got the following:

```
$ grunt test
Running "phpunit:classes" (phpunit) task
Starting phpunit (target: classes) in tests/phpunit/
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from /Users/Luke/Desktop/test-plugin/phpunit.xml.dist



Time: 115 ms, Memory: 8.00Mb

No tests executed!

Running "qunit:all" (qunit) task
Testing tests/qunit/my-plugin.html 
>> PhantomJS timed out, possibly due to a missing QUnit start() call.
Warning: 1/1 assertions failed (0ms) Use --force to continue.

Aborted due to warnings.
Beast-Pro:test-plugin Luke$ grunt test
Running "phpunit:classes" (phpunit) task
Starting phpunit (target: classes) in tests/phpunit/
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from /Users/Luke/Desktop/test-plugin/phpunit.xml.dist



Time: 114 ms, Memory: 8.00Mb

No tests executed!

Running "qunit:all" (qunit) task
Testing tests/qunit/my-plugin.html 
>> PhantomJS timed out, possibly due to a missing QUnit start() call.
Warning: 1/1 assertions failed (0ms) Use --force to continue.

Aborted due to warnings.
```

**Comment by lamosty** [comment]
I [found out](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html) that if I refactor `Core_Tests` in `tests/phpunit/` to `CoreTest`, PHP Unit testing runs successfully.

**Comment by morganestes** [comment]
I noticed recently that QUnit is getting installed via npm, but is trying to load the bower version of the scripts. I patched this in a private repo and can work on a patch for it here.
