### ISSUE TITLE
Grunt copy failing: Warning: Unable to write "release..." file (Error code: EISDIR)

### ISSUE THREAD

**Issue by lamosty** [10up/generator-wp-make#16]
I was getting this error with default Gruntfile.js during `grunt build` process. Found out you need to add `expand: true` to the copy task:

```
copy: {
   main: {
      src: [....],
      dest: '...',
      expand: true
   }
}
```

**Comment by colegeissinger** [comment]
I am also having this same issue.

**Comment by NicoleGeissinger** [comment]
I am also having this same issue.

**Comment by lkwdwrd** [comment]
#6 hasn't gotten any love yet. The build task was in need of some attention before, but then @ericmann did some great work refactoring and I imagine it will need even more work now. Also #11 would be good to help make sure this doesn't happen in the future.

**Comment by lkwdwrd** [comment]
closing as the build task will be rewritten as part of the V1 build.
