### ISSUE TITLE
Grunt Build results in EISDIR error

### ISSUE THREAD

**Issue by NicoleGeissinger** [10up/generator-wp-make#17]
When I ran `grunt build` for the first time on a brand new set of files, I was greeted with this message in copy:main `Unable to write "release/0.0.1/assets" file (Error code: EISDIR). Use --force to continue.`.

Adding `expand: true` to the copy:main task corrected that.

**Comment by lamosty** [comment]
I [reported](https://github.com/10up/generator-wp-make/issues/16) the same issue yesterday.

**Comment by NicoleGeissinger** [comment]
ah thanks, I over looked that issue. I'll close this out and +1 your issue :) Thansk!
