### ISSUE TITLE
When population the description while generating a plugin the description prompt keep repeating on each key press.

### ISSUE THREAD

**Issue by ivanlopez** [10up/generator-wp-make#21]
I've gone through the process of making several test plugins and its only this prompt that repeats.

![screen shot 2015-04-23 at 9 10 37 pm](https://cloud.githubusercontent.com/assets/1428016/7310641/a4f0cfb8-e9fd-11e4-92e8-5de4e43bd469.png)

**Comment by lkwdwrd** [comment]
@ivanlopez I've been unable to reproduce the issue, can you give some more detail of the circumstances you're seeing this in? Versions of the various dependencies, etc.?

**Comment by ericmann** [comment]
This is a Yeoman bug, not an us bug. They're currently working on fixing it.
