### ISSUE TITLE
Introduce .editorconfig in generator package

### ISSUE THREAD

**Issue by unfulvio** [10up/generator-wp-make#28]
This is a nifty generator, I love it

would you consider introducing for :plugin or :theme a .editorconfig file for WordPress standards?

http://editorconfig.org/

possible .editorconfig settings:

https://gist.github.com/nekojira/7ef529df4560c7f4d03d

**Comment by jonathantneal** [comment]
Will Markdown files need an exception for line returns? http://markdown-guide.readthedocs.org/en/latest/basics.html#line-return

**Comment by ericmann** [comment]
That's a good question. I literally just ported the `.editorconfig` from core to the project.

**Comment by ericmann** [comment]
See https://develop.svn.wordpress.org/trunk/.editorconfig If there are any other changes we should make, feel free to submit a PR. But for a default config file, I think this would be fine. 80-20 rule and all that.
