### ISSUE TITLE
#_is deprecated

### ISSUE THREAD

**Issue by dabrattoli** [10up/generator-wp-make#32]
When I try to use wp-make I receive an error saying that "#_ is deprecated. Require  your own version of Lodash or underscore.string". I have tried different methods and have been unable to get either Lodash, underscore or wp-make to work. Any additional instructions on how to handle this issue would be greatly appreciated.Thank you for your time and consideration.

**Comment by alessandrotesoro** [comment]
Getting same issue here :/

**Comment by dabrattoli** [comment]
![screenshot_wpmake_error](https://cloud.githubusercontent.com/assets/12447142/8549554/687d8216-2499-11e5-881d-f17f0664e76e.JPG)

I tried to use the wp-make generator today after restarting my computer and still get the #_is deprecated error as seen in the screenshot above. The I am running Windows 7 pro 64-bit with these local versions
yo 1.4.7
bower 1.4.1
npm 2.12.0
node 0.12.2
git 1.9.2
wp-make version 0.2.0

Any help you can give will be greatly appreciated. Thank you.

**Comment by lkwdwrd** [comment]
Just pushed out 0.2.1 which should fix this error. Can you please update and give it another try?

**Comment by lkwdwrd** [comment]
Closing as I've not hear this pop back up since 0.2.1.
