### ISSUE TITLE
Template JSON with JS objects

### ISSUE THREAD

**Issue by lkwdwrd** [10up/generator-wp-make#34]
Right now, the JSON configuration files are created through underscores string templating. This seems a bit silly since I've found it's prone to syntax errors if I'm not very careful about how it's being output. We should consider actually building the object in JS, then outputting it into a file with JSON.stringify or similar.

**Comment by lkwdwrd** [comment]
closing as this will be part of the V1 feature set.

**Comment by jonathantneal** [comment]
This is great news!
