### ISSUE TITLE
Return types don't need a trailing period

### ISSUE THREAD

**Issue by morganestes** [10up/generator-wp-make#37]
The generator adds a `@return` statement for every method, even when it's not specifically required.
This is good. :clap: 

It ends the return type with a full stop (e.g. `@return void.`), which isn't exactly forbidden by the [PHP-FIG proposed standards for docs](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#815-return), but doesn't follow the example.

I propose adjusting the generator to keep the return statements, even if they're not required (yea!), but remove the full stop (boo!).

**Comment by ericmann** [comment]
Fixed by #38
