### ISSUE TITLE
Include Body Class Function

### ISSUE THREAD

**Issue by allenmoore** [10up/generator-wp-make#46]
While creating a new theme from the generator, I noticed that body classes were not being added to the `<body>` element. I looked at the theme files being added by the generator and saw that header.php in _theme > templates > theme_ does not include the body class in the `<body>` element.

I've fixed this in a fix branch and have submitted a pull request. The pull request can be found here -- [fix/issue-46](https://github.com/10up/generator-wp-make/pull/47).

**Comment by ericmann** [comment]
We don't need an issue _and_ a PR ;-) Closing this as a dupe of #47.
