### ISSUE TITLE
Remove Humans.txt

### ISSUE THREAD

**Issue by NicoleGeissinger** [10up/generator-wp-make#50]
In discussions with @tlovett1 and @lkwdwrd , we found that we are launching sites with the humans.txt when we shouldn't have. Of course this could be manually avoided, but I think it's worth noting that we might just want to remove this or possibly provide an option to opt-out of the humans.txt for certain sites.

**Comment by ericmann** [comment]
The option to opt-out of `humans.txt` is coming with PR #59.
