### ISSUE TITLE
Special characters in title of plugin not converting right for namespacing

### ISSUE THREAD

**Issue by NicoleGeissinger** [10up/generator-wp-make#52]
I just created a plugin that had a colon in it. It appears when the title contains special characters, these aren't being stripped from the title when it is converted to the namespacing within the code. Creating fatal errors :(

E.G.
Title: 10up: Awesome Plugin
Result in the code: TenUp\10up:_awesome_plugin\Core\setup();

**Comment by Takeno** [comment]
:+1:
It converted my namespace in: La_Retina_d&#39;Oro
