### ISSUE TITLE
SASS import & Auto Reload

### ISSUE THREAD

**Issue by wrux** [10up/generator-wp-make#53]
I'm new to using bower and that so these two questions may seem a bit stupid but here goes:
- I have setup a clean theme and I have installed `bower-compass-bootstrap` with the -save flag. When I am in the sass file how do I import that? Anything I try isn't working. 
- Also how do I get live reload working on this? Is it included? I've just been trying to use `grunt` without watch just as a test. 

I really like your theme generator as a startup. I just need maybe something more of an introduction seeing as i'm not familiar with grunt and that. Can anybody shine some light on this for me please? That would be much appreciated.

**Comment by pattiereaves** [comment]
@wrux I'm trying to figure out how to automatically insert bower_components, too. [This link](http://connelhooley.uk/blog/getting-wordpress-gruntjs-and-bower-to-get-along/) was really helpful, but I'm still not there. 

Here's how far I got: I wrote a [grunt-wiredep](https://github.com/stephenplusplus/grunt-wiredep) task to automatically insert JS and CSS bower_components.

## Create tasks/options/wiredep.js

```
module.exports = {
  theme: {
    src: [
      'includes/functions/enqueue_scripts.php',
      'assets/css/sass/my_theme.scss'
    ],
    exclude: [ 
        "bower_components/jquery"
    ],
    fileTypes: {
      php: {
        block: /(([ \t]*)\/\/\s*bower:*(\S*))(\n|\r|.)*?(\/\/\s*endbower)/gi,
        detect: {
          js: /wp_enqueue_script\(['"]([^'"]+)/gi,
          css: /wp_enqueue_style\(['"]([^'"]+)/gi
        },
        replace: {
          js: function (filePath) {
            return 'wp_enqueue_script(\'' + filePath + '\', get_stylesheet_directory_uri() . \'/' + filePath + '\', false, false, true);'
          },
          css: function (filePath) {
            return 'wp_enqueue_style(\'' + filePath + '\', get_stylesheet_directory_uri() . \'/' + filePath + '\');'
          },
        },
      },
      scss: {
        replace: {
          css: '@import "../{{filePath}}";',
          sass: '@import "../{{filePath}}";',
          scss: '@import "../{{filePath}}";'
        }
      }
    }
  }
};
```

## add the following inside your tasks/options/watch.js

```
bower: {
        files: ['bower.json'],
        tasks: ['wiredep:theme']
    },
    livereload: {
        files: ['assets/css/*.css'],
        options: {
            livereload: 35729 //this will fix your livereload problem, too
        }
    },
```

## Create includes/functions/enqueue_scripts.php

```
<?php

//Enqueue scripts
if (!function_exists('my_theme_bower_scripts')) :
function theme_name_bower_scripts() {
  // bower:js
  // endbower
}
add_action('wp_enqueue_scripts', 'my_theme_bower_scripts');
endif;

//Enqueue styles
if (!function_exists('my_theme_bower_styles')) :
function my_theme_bower_styles() {
  // bower:css
  // endbower
}
add_action('wp_enqueue_scripts', 'my_theme_bower_styles');
endif;
```

## add to css/sass/my_theme.scss

```
//Include bower components
// bower:scss
// endbower
```

Hypothetically this should work, and when I run `grunt wiredep -v -d`, I get no errors:

```
Running "wiredep:theme" (wiredep) task
[D] Task source: /Library/WebServer/Documents/wp/wp-content/themes/my_theme/node_modules/grunt-wiredep/tasks/wiredep.js
Verifying property wiredep.theme exists in config...OK
Files: includes/functions/enqueue_scripts.php, assets/css/sass/my_theme.scss
Verifying property wiredep.theme.src exists in config...OK
Options: src=["includes/functions/enqueue_scripts.php","assets/css/sass/my_theme.scss"], exclude=["bower_components/jquery"], fileTypes={"php":{"block":{},"detect":{"js":{},"css":{}},"replace":{}},"scss":{"replace":{"css":"@import \"../{{filePath}}\";","sass":"@import \"../{{filePath}}\";","scss":"@import \"../{{filePath}}\";"}}}, onError=undefined, onFileUpdated=undefined, onPathInjected=undefined, onMainNotFound=undefined

Done, without errors. 
```

But, my stuff never gets updated. Putting this out there in case someone listening somewhere on the Internet has an idea ...

**Comment by pattiereaves** [comment]
I figured it out! That works! :smile_cat: 

Make sure you're [saving your dependencies in bower.json as "dependencies" and not "devDependencies"](http://stackoverflow.com/questions/25898106/yeoman-grunt-wiredep-not-injecting-dependencies) ... :dancer: Only a few hours later ...
