### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by rohitmanglik** [10up/generator-wp-make#66]
Hi, 

I installed plugin using wp-make (with autoprefixed and without sass) as per the instructions in the readme file and got following issues:

1) bower.json:5 has an extra brace.
2) While running "grunt" task, I got following warning:
"No postcss targets found".

**Comment by ericmann** [comment]
The first error was a typo in the generated `bower.json` file. It's been corrected.

As for the postcss issue, take a look at your `/tasks/options/postcss.js` file and define the files you need processed appropriately.
