### ISSUE TITLE
Switch to namespaces

### ISSUE THREAD

**Issue by lkwdwrd** [10up/generator-wp-make#7]
The generator created namespace classes to get everything started in themes and plugins. However, this is a bit backwards at this point. Instead it should generate namespaces to help push us into the future. These are more easily converted to namespace classes if for some reason we need 5.2 compat.

It should be noted, that each of the items in the namespace classes had a PHP Unit Test written for it as an example. In addition to moving the generated files to namespaces, the example tests need to be migrated and updated as well.

**Comment by ericmann** [comment]
Commits through b97f7988e995c6747a47c563ad111cc4ad8fa0d8 update plugins as requested.

**Comment by ericmann** [comment]
Plugin and both the parent and child theme are updated accordingly.
