### ISSUE TITLE
Change default domain from .dev to .local

### ISSUE THREAD

**Issue by emeaguiar** [10up/generator-wp-make#79]
So this discussion came up in a chat a while ago, apparently .dev is a real domain owned by google, however it's default when using wp-make... should we change it to be .local which is reserved for local environments?

**Comment by bswatson** [comment]
If we change this, I would recommend moving it to .localhost as it is one of the four reserved TLDs based on https://tools.ietf.org/html/rfc6761.

.test
.example
.invalid
.localhost

**Comment by lkwdwrd** [comment]
I'm not remembering where Make sets a specific domian?

Luke Woodward – Associate Director of Engineering
10up Inc. http://10up.com | luke.woodward@10up.com | @lkwdwrd

**Comment by morganestes** [comment]
There's been some debate over this over at [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/583). Based on that and other conversations, I think `.localhost` is the way to go, but I get the feeling VVV may end up with `.local`.

**Comment by fuhton** [comment]
WP Make does not 'make' (see what I did there?) any recommendations or assumptions for any type of site setup or local development urls. Closing.
