### ISSUE TITLE
Namespace not imported

### ISSUE THREAD

**Issue by arulpr** [10up/generator-wp-make#89]
I tried the wp make plugin sub generator and noticed that the plugin generator didn't import namespace declared in includes core.php into the plugin index 

`use NameSpace;` is missing

**Comment by lkwdwrd** [comment]
Sorry for the somewhat delayed response @arulpr -- we've been working really hard to transform this generator into something that will take us into the next several years. To that end, the legacy version (currently in master) is not receiving any updates at this time unless they come in the form of pull requests.

All of the generators are being 100% rewritten in version one, so this particular issue should be cleaned up as well.

I'm going to close this issue in anticipation of version 1, but if you would like to send a PR to fix, or if it does find it's way into V1 after release, please don't hesitate to let us know!

Thanks for generating with us 💯
