### ISSUE TITLE
Consider libsass

### ISSUE THREAD

**Issue by lkwdwrd** [10up/generator-wp-make#9]
The front end world seems to be talking more and more about [libsass](https://github.com/sass/libsass). It may be worth embracing this as a means of speeding up builds. There is a [node wrapper](https://github.com/sass/node-sass) that might make this an easy transition. There is also a [grunt-sass](https://github.com/sindresorhus/grunt-sass) plugin that makes use of libsass, though if we look at broccoli this may not be the direction we want to go.

**Comment by ericmann** [comment]
Already merged in the switch to grunt-sass as autoprefixer is officially deprecated.
